[project]
name = "tracer-runtime-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "orjson>=3.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
